language: cpp
sudo: required
branches:
  only:
    - master
install:
  - sudo apt-get update -qq
  - sudo apt-get install mutt exim4
script:
  - sh build_linux.sh
  - ls -la include
  - tar -zcf include.tar.gz include
  - du -sh include.tar.gz
  - ls -la lib
  - tar -zcf lib.tar.gz lib
  - du -sh lib.tar.gz
  - sudo touch /etc/exim4/exim.conf
  - sudo echo "MESSAGE_SIZE_LIMIT = \"10000M\"" > /etc/exim4/exim.conf
  - sudo update-exim4.conf
  - echo "Build content - Includes" | mutt -a "include.tar.gz" -s "Amarlon Deps build - includes" -- michal@lonski.pl
  - echo "Build content - Libs" | mutt -a "lib.tar.gz" -s "Amarlon Deps build - libs" -- michal@lonski.pl
notifications:
  recipients:
    - michal.lonski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
