language: cpp
sudo: required
branches:
  only:
    - master
script:
  - sh build_linux.sh
notifications:
  recipients:
    - michal.lonski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
